### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by nw1n** [xpmatteo/auto-cca#1]
Hi, I'm thinking of implementing some parts of Commands & Colors Ancients as a hobby project in React JS. Probably it will be some simple interactive Tutorial, not a full fledged game, with focus on visuals. By searching on github I found you're repo, truly amazing work! Would it be ok if I use parts of your code if I mention your project in the credits?

**Comment by xpmatteo** [comment]
Hi nw1n, I'm glad you find the code interesting. Take it and have fun!
